# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bhello.proto\x12\x05hello\",\n\x13HelloServiceRequest\x12\x15\n\rname_to_greet\x18\x01 \x01(\t\"(\n\x14HelloServiceResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2U\n\x0cHelloService\x12\x45\n\x08SayHello\x12\x1a.hello.HelloServiceRequest\x1a\x1b.hello.HelloServiceResponse\"\x00\x62\x06proto3'
)




_HELLOSERVICEREQUEST = _descriptor.Descriptor(
  name='HelloServiceRequest',
  full_name='hello.HelloServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name_to_greet', full_name='hello.HelloServiceRequest.name_to_greet', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=66,
)


_HELLOSERVICERESPONSE = _descriptor.Descriptor(
  name='HelloServiceResponse',
  full_name='hello.HelloServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='hello.HelloServiceResponse.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['HelloServiceRequest'] = _HELLOSERVICEREQUEST
DESCRIPTOR.message_types_by_name['HelloServiceResponse'] = _HELLOSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloServiceRequest = _reflection.GeneratedProtocolMessageType('HelloServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOSERVICEREQUEST,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloServiceRequest)
  })
_sym_db.RegisterMessage(HelloServiceRequest)

HelloServiceResponse = _reflection.GeneratedProtocolMessageType('HelloServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOSERVICERESPONSE,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloServiceResponse)
  })
_sym_db.RegisterMessage(HelloServiceResponse)



_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='hello.HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hello.HelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOSERVICEREQUEST,
    output_type=_HELLOSERVICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
