# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\",\n\x13HelloServiceRequest\x12\x15\n\rname_to_greet\x18\x01 \x01(\t\"(\n\x14HelloServiceResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2U\n\x0cHelloService\x12\x45\n\x08SayHello\x12\x1a.hello.HelloServiceRequest\x1a\x1b.hello.HelloServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOSERVICEREQUEST']._serialized_start=22
  _globals['_HELLOSERVICEREQUEST']._serialized_end=66
  _globals['_HELLOSERVICERESPONSE']._serialized_start=68
  _globals['_HELLOSERVICERESPONSE']._serialized_end=108
  _globals['_HELLOSERVICE']._serialized_start=110
  _globals['_HELLOSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
