# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\xa1\x01\n\x08Purchase\x12\x13\n\x0bpurchase_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x05\x12\x10\n\x08\x61rticles\x18\x03 \x03(\x05\x12\x13\n\x0btotal_price\x18\x04 \x01(\x01\x12$\n\x04type\x18\x05 \x01(\x0e\x32\x16.example.Purchase.Type\"\x1e\n\x04Type\x12\n\n\x06ONLINE\x10\x00\x12\n\n\x06RETAIL\x10\x01\"\x8e\x01\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66orename\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0b\n\x03ssn\x18\x04 \x01(\x05\x12\x10\n\x08zip_code\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12$\n\tpurchases\x18\x07 \x03(\x0b\x32\x11.example.Purchase\"g\n\x17\x43ustomerServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12$\n\tcustomers\x18\x03 \x03(\x0b\x32\x11.example.Customer\"M\n\x0ePurchaseResult\x12\x13\n\x0bpurchase_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"%\n\x0f\x41mountThreshold\x12\x12\n\nmin_amount\x18\x01 \x01(\x01\x32\xd8\x01\n\x0f\x43ustomerService\x12\x42\n\x0b\x41\x64\x64\x43ustomer\x12\x11.example.Customer\x1a .example.CustomerServiceResponse\x12?\n\rSendPurchases\x12\x11.example.Purchase\x1a\x17.example.PurchaseResult(\x01\x30\x01\x12@\n\x0fGetHighSpenders\x12\x18.example.AmountThreshold\x1a\x11.example.Customer0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PURCHASE']._serialized_start=27
  _globals['_PURCHASE']._serialized_end=188
  _globals['_PURCHASE_TYPE']._serialized_start=158
  _globals['_PURCHASE_TYPE']._serialized_end=188
  _globals['_CUSTOMER']._serialized_start=191
  _globals['_CUSTOMER']._serialized_end=333
  _globals['_CUSTOMERSERVICERESPONSE']._serialized_start=335
  _globals['_CUSTOMERSERVICERESPONSE']._serialized_end=438
  _globals['_PURCHASERESULT']._serialized_start=440
  _globals['_PURCHASERESULT']._serialized_end=517
  _globals['_AMOUNTTHRESHOLD']._serialized_start=519
  _globals['_AMOUNTTHRESHOLD']._serialized_end=556
  _globals['_CUSTOMERSERVICE']._serialized_start=559
  _globals['_CUSTOMERSERVICE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
