# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import example_pb2 as example__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in example_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerServiceStub(object):
    """
    Main service for customer administration

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddCustomer = channel.unary_unary(
                '/example.CustomerService/AddCustomer',
                request_serializer=example__pb2.Customer.SerializeToString,
                response_deserializer=example__pb2.CustomerServiceResponse.FromString,
                _registered_method=True)
        self.SendPurchases = channel.stream_stream(
                '/example.CustomerService/SendPurchases',
                request_serializer=example__pb2.Purchase.SerializeToString,
                response_deserializer=example__pb2.PurchaseResult.FromString,
                _registered_method=True)
        self.GetHighSpenders = channel.unary_stream(
                '/example.CustomerService/GetHighSpenders',
                request_serializer=example__pb2.AmountThreshold.SerializeToString,
                response_deserializer=example__pb2.Customer.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """
    Main service for customer administration

    """

    def AddCustomer(self, request, context):
        """
        Adds a new customer

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPurchases(self, request_iterator, context):
        """
        Task 1: client streams Purchases, server streams back one PurchaseResult per Purchase

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHighSpenders(self, request, context):
        """
        Task 2: server streams back all customers whose total spend exceeds min_amount

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomer,
                    request_deserializer=example__pb2.Customer.FromString,
                    response_serializer=example__pb2.CustomerServiceResponse.SerializeToString,
            ),
            'SendPurchases': grpc.stream_stream_rpc_method_handler(
                    servicer.SendPurchases,
                    request_deserializer=example__pb2.Purchase.FromString,
                    response_serializer=example__pb2.PurchaseResult.SerializeToString,
            ),
            'GetHighSpenders': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHighSpenders,
                    request_deserializer=example__pb2.AmountThreshold.FromString,
                    response_serializer=example__pb2.Customer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('example.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """
    Main service for customer administration

    """

    @staticmethod
    def AddCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/example.CustomerService/AddCustomer',
            example__pb2.Customer.SerializeToString,
            example__pb2.CustomerServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPurchases(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/example.CustomerService/SendPurchases',
            example__pb2.Purchase.SerializeToString,
            example__pb2.PurchaseResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHighSpenders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/example.CustomerService/GetHighSpenders',
            example__pb2.AmountThreshold.SerializeToString,
            example__pb2.Customer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
